languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "DaveSaah's Portfolio"

[params]
dateFormat = "2 January 2006"

description = "Portfolio website of David Saah, Linux geek and software engineer"

[params.author]
name = "David Saah"
image = "img/author.jpeg"
headline = "Linux Geek & Software Engineer"
bio = "Portfolio website of David Saah, Linux geek and software engineer"
links = [
  { email = "mailto:davesaah@gmail.com" },
  { github = "https://github.com/DaveSaah" },
  { pencil = "https://davesaah.substack.com" },
  { x-twitter = "https://x.com/davesaah_" },
  { linkedin = "https://linkedin.com/in/davesaah" },
  { link = "https://www.upwork.com/freelancers/~011b9cd52fa211c6a0" },
]
