languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "DaveSaah's Portfolio"

[params]
dateFormat = "2 January 2006"

description = "Portfolio website of David Saah, Linux geek and software engineer"

[params.author]
name = "David Saah"
image = "img/author.jpeg"
headline = "Linux Geek & Software Engineer"
bio = "Portfolio website of David Saah, Linux geek and software engineer"
links = [
  { email = "mailto:saahdavid17@gmail.com" },
  { github = "https://github.com/DaveSaah" },
  { link = "https://davesaah.substack.com" },
  { linkedin = "https://linkedin.com/in/davesaah" },
  { globe = "https://wakatime.com/@DaveSaah" },
]
